# ================================================
# updating_config.yaml
# 用於設定 Excel 更新腳本的通知、日誌、檔案密碼及進階行為
# ================================================

# === [1] 通知電郵收件人設定 ===
# email_recipients: 當更新腳本完成（或出錯）時要通知的收件人清單。
# - to: 主要收件人（必填），可多個
# - cc: 副本收件人（可選），可多個
# - bcc: 密件副本收件人（可選），可多個
email_recipients:
  to: ["your_email@example.com"]      # # 主收件人列表 ["your_email@example.com"] 或 ["your_email@example.com", "colleague@example.com"]
  cc: []                             # 副本收件人清單
  bcc: []                            # 密件副本清單

# === [2] 電郵主旨前綴設定 ===
# email_subject_prefix: 發送通知電郵時，主旨會加上此前綴字，有助辨認來源
email_subject_prefix: "K Chain File Refresh Completion Notification"

# === [3] 日誌檔案儲存路徑 ===
# log_directory: 執行記錄和錯誤日誌會存於這個資料夾
log_directory: "D:\\Pzone\\log"

# === [4] Excel 檔案個別設定 ===
# file_configs: 每個 Excel 檔案可指定需要執行的 macro 及密碼（如有）
# - macro: 指定 macro 名稱（如需執行）。無需 macro 請填 null。
# - open_password: 開啟 Excel 時需要的密碼。建議用環境變數或 .env 取值，避免明文存密碼。
# - write_password: 儲存 Excel 時需要的密碼。建議用環境變數或 .env 取值。
file_configs:
  Data - All:
    macro: null                       # 不需執行 macro
    open_password: null               # 開啟密碼（建議用環境變數）
    write_password: "aaaabbbbbccc"    # 儲存密碼（建議用環境變數）
  Chain Summary:
    macro: null
    open_password: null
    write_password: "aaaabbbbbccc"    # 儲存密碼（建議用環境變數）
  BM Compare:
    macro: "Main"                     # 需執行 macro「Main」
    open_password: null
    write_password: null

# === [5] 進階設定 ===
# advanced_settings: 控制腳本運行細節
# - max_retries: 操作失敗時最多重試次數（如開檔或儲存失敗）
# - retry_delay_base: 重試延遲基數（秒），每次失敗等待時間會指數型增加
# - excel_visible: Excel 是否顯示介面（True=顯示，False=背景運行）
# - force_calculation: 是否強制刷新所有公式
advanced_settings:
  max_retries: 3                      # 失敗時最多重試3次
  retry_delay_base: 2                 # 第一次失敗等2秒，第二次4秒，第三次8秒
  excel_visible: True                 # Excel介面可見（DEBUG用），自動化可設為 False
  force_calculation: True             # 強制刷新所有公式

# === [備註] ===
# - 密碼等敏感資訊請不要 commit 在 repo，建議用 null 並於執行時由環境變數或 .env file 讀入。
# - 若要用 .env 檔案，請加到 .gitignore 防止上傳。
# - 如需更多檔案規則，可於 file_configs 加新項目。
# - 所有路徑請用雙反斜線（\\）或正確 escape。
